---
title: "Enunciados"
author: "Maria Caballos"
date: '2023-10-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cada integrante del grupo propondrá un enunciado de un problema y su
resolución empleando todos los métodos de incertidumbre.



# Ejercicio 1 (María Caballos Galindo)

María, amante de los viajes y casas rurales, decide organizar uno a cualquier destino para el mes de julio. Se encuentra con varias opciones a considerar para ella y su grupo de amigos. El viaje será de 4 noches y 5 dias.

En primer lugar, encuentra una casa rural en la Sierra de Sevilla, teniendo en cuenta que María y sus amigos son de la provincia, la gasolina no les supondrá un gasto mayor de 30€. El valor de la casa es de 120€/noche. El propietario ha decidido ofertar una tarifa interesante: descuento del 10% si el número de individuos es mayor de 15 personas y del 15% si supera a 20 individuos.

De segunda opción nos topamos con una casa rural en la provincia de Cádiz. El precio de la gasolina hasta dicho lugar asciende a 45€. El precio de esta casa es de 98€/noche. Si el grupo es de 20 individuos o superior, se regala una noche.

Por otro lado, descubrimos una casa en un pueblo de Málaga por el valor de 100€ la noche independientemente del número de personas. El precio de la gasolina trata de unos 38€. 

Decidir cuál es la mejor alternativa según todos los criterios si lo que quiere María es gastarse el menos dinero posible, pero a la vez, pasar una estancia agradable con sus amigos.


# Ejercicio 2 (Julia López Sacramento)

Una chica apasionada por el baile está buscando una academia para mejorar sus 
habilidades. En su ciudad, hay tres academias de baile populares, cada una con 
un costo diferente de matrícula y mensualidad. La chica quiere tomar la mejor
decisión para aprender a bailar sin gastar demasiado dinero.

Academia A: Ofrece clases de alta calidad y tiene una excelente reputación en 
la comunidad. Sin embargo, el costo de la matrícula es de 50€ y la 
mensualidad es de 45€ por estilo, pero si se apunta a 2 estilos la matricula 
le saldría 65€ y en el caso de 3 estilos se regala la matrícula y la 
mensualidad pasa a ser de 100€

Academia B: Es conocida por tener instructores experimentados y se encuentra a 
una distancia conveniente de su hogar. La matrícula es de 35€, pero la 
mensualidad es de 55€, en cambio si escoge 2 estilos el precio de la mensualidad
solo subiría a 60€. Además si escoge 3 estilos solo paga 10€ de matrícula,
y la mensualidad sube a 80€

Academia C: Ofrece tarifas muy asequibles con una matrícula de 20€ y una 
mensualidad de 30€, pero la calidad de enseñanza puede variar y algunos dicen 
que es irregular. En caso de 3 estilos la matrícula le saldría 15€ y la 
mensualidad el triple

Decidir cuál es la mejor alternativa según todos los criterios si la chica 
quiere aprender a bailar de manera efectiva y minimizar sus gastos. 


#Ejercicio 3 (Estefanía BLanco Rodríguez)
Un consumidor quiere hacer la compra semanal pero tiene varias opciones de supermercados
en su ciudad. Debe considerar los factores que incluyen cada opción y tomar
la decisión de en que supermercado le saldría más rentable en su conjunto
de hacer la compra, teniendo en cuenta que quiere gastarse la menor cantidad de 
dinero posible.

En el supermercado 1, el costo total de la compra le saldría aproximadamente
65€. Se encuentra a 3 minutos en tren, que le saldría un costo de 2€, a 10 minutos 
aproximadamente en coche, con un costo de 3€ la gasolina, y a 15 minutos en bus
con un costo del billete de 1,2€. El consumidor es socio de 
este supermercado y le hacen un 10% de descuento en el precio de su compra.

En el supermercado 2, el costo total de la compra saldría de 50€, pero la distancia
de su domicilio al supermercado es mayor que la anterior y le supondría un gasto de gasolina de 5€ si va en coche, 2,50€ si va en tren y 1,4€ si va en bus.

Y por último, en el supermercado 3, la compra le saldría por un 
costo total de 70€. La ubicación de dicho supermercado también esta lejos
de su casa pero tiene la opción de ir en bus que solo le supondría un 
precio de 1.2€, si va en coche le cuesta un total de 3€ la gasolina, y si decide
ir en tren le supondria un coste de 2,2€. El consumidor tiene
el carnet de familia numerosa y en este supermercado le proporciona un descuento
del 21%.

El objetivo es tomar la decisión de cual es la mejor alternativa 
teniendo en cuenta cada uno de los factores de cada supermercado.



#Ejercicio 4 (Sergio Canto García)

La federación nacional española de triatlón debe presentar la lista de deportistas convocadas para participar en el campeonato femenino europeo de triatlón.

Debe llevar 5 personas, y hasta ahora ya tiene 4 seleccionadas. Para el último puesto que queda disponible, tiene tres deportistas candidatas, las cuales tienen puntuaciones en cada una de las disciplinas (natación, maratón y ciclismo, calculadas sobre 100). 

Rocio Martín es una atleta extremeña que en natación tiene una puntuación de 55, en maratón 78 y en ciclismo 81.

Clara González, de Barcelona, tiene unas puntuaciones de 66 en natación, 77 en maratón y 74 en ciclismo. 

Carmen Puerto tiene puntuación de 80 en natación, 62 en maratón y 73 en ciclismo. 

Decidir qué atleta debe ser seleccionada para la competición.
